[package]
name = "sol2js"
version = "0.1.0"
edition = "2024"

# wasm-pack build --target web

[dependencies]
flash-lso = { path = "../flash-lso", features = ["serde", "flex"] }
serde_json = "1"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]